In [1]:
import numpy as np

In [37]:
M = np.fromstring("""827.065308 534.284729 -174.653351 -33.243122
-493.187958 540.785156 -683.285461 213.997589
-271.460236 651.112305 710.682983 -4.843169
0.000000 0.000000 0.000000 1.000000""", sep=' ').reshape(4, 4)
M

array([[ 827.065308,  534.284729, -174.653351,  -33.243122],
       [-493.187958,  540.785156, -683.285461,  213.997589],
       [-271.460236,  651.112305,  710.682983,   -4.843169],
       [   0.      ,    0.      ,    0.      ,    1.      ]])

In [38]:
v = np.array([1, 0, 0, 1]).reshape(4)
v

array([1, 0, 0, 1])

In [39]:
a = M.dot(v)
a /= a[3]
a

array([ 793.822186, -279.190369, -276.303405,    1.      ])

In [40]:
np.linalg.norm(a[:3])

885.688713229862

In [33]:
np.linalg.norm(a[:3])

886.5244407443795

In [42]:
885.688713229862/886.5244407443795

0.9990572989574705